#!/bin/sh
#
#    Copyright (C) 2013  Rubén Rodríguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=3
EXTERNAL="deb-src http://archive.ubuntu.com/ubuntu quantal main universe"

. ./config

#patch -p1 < $DATA/ccallback.patch

sed 's/1\.33\.14/1\.3\.14/' configure.ac -i
/bin/sed 's/1\.33\.9/1\.3\.9/' debian/control* -i
apt-get install -q -y pep8 pyflakes

changelog "GNOME bug 644926"

compile

